name: 'Cleanup PR Branch'

on:
  delete

jobs:
  cleanup-pr-branch:
    name: 'Delete PR Branch on Delete'
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Install TakeShape tools
        run: |
          npm install --quiet @takeshape/nextjs --global

      - name: Delete branch
        run: |
          takeshape-branch-delete --name ${{ github.event.ref }}
        env:
          TAKESHAPE_API_KEY: ${{ secrets.TAKESHAPE_API_KEY }}
